title: "化学の伝道師：　西園寺聖樹のWebページ"
description: "化学", "予備校講師", "塾講師", "自然科学", "わかりやすい化学"

remote_theme: pmarsceill/just-the-docs 
github_repo_url: "https://saionji-chem.github.io/"

heading_anchors: true

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-sitemap
